# Generated by Django 5.0 on 2023-12-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_remove_orderinvestment_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
        ),
    ]
