# Generated by Django 5.0 on 2023-12-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('quality', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_images', models.ImageField(default='default_image.jpg', upload_to='product_assistance_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_AssistanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_assistance_images/')),
                ('product_assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assistance_images', to='imports.product_assistance')),
            ],
        ),
    ]
