# Generated by Django 5.0 on 2023-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_collaboration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='whatsapp',
            field=models.CharField(default='', max_length=15),
        ),
    ]
