# Generated by Django 5.0 on 2023-12-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0009_product_assistance_user_product_assistance_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('number', models.CharField(default='', max_length=15)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
